// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rldqgiigzythoisrxcvj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJsZHFnaWlnenl0aG9pc3J4Y3ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2MTQ3OTUsImV4cCI6MjA2MjE5MDc5NX0.kzxeGbUWTKL2xrjbAQQUIflbGHy6TPLp-nFma89WBzo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);